/**
 * Seed the players table from the static squads JSON.
 *
 * Run with: node --experimental-strip-types scripts/seed-players.ts
 *
 * Requires DATABASE_URL in .env.local
 * Data source: scripts/data/squads.json (generated by fetch-squads.ts)
 */

import { readFileSync } from "fs";

const envFile = readFileSync(".env.local", "utf-8");
for (const line of envFile.split("\n")) {
  const match = line.match(/^([^#=]+)=["']?(.+?)["']?$/);
  if (match) process.env[match[1].trim()] = match[2].trim();
}

interface SquadPlayer {
  teamCode: string;
  teamName: string;
  name: string;
  position: string;
  number: number;
}

async function main() {
  const squadsPath = "scripts/data/squads.json";
  const players: SquadPlayer[] = JSON.parse(readFileSync(squadsPath, "utf-8"));
  console.log(`Loaded ${players.length} players from ${squadsPath}`);

  const { neon } = await import("@neondatabase/serverless");
  const sql = neon(process.env.DATABASE_URL!);

  await sql`DELETE FROM players`;
  console.log("Cleared existing players.\nSeeding database...\n");
  let inserted = 0;
  let failed = 0;
  const teamCounts: Record<string, number> = {};

  for (const p of players) {
    try {
      await sql`
        INSERT INTO players (team_id, name, position, number)
        VALUES (${p.teamCode}, ${p.name}, ${p.position}, ${p.number})
        ON CONFLICT (team_id, name) DO UPDATE SET position = ${p.position}, number = ${p.number}
      `;
      inserted++;
      teamCounts[p.teamCode] = (teamCounts[p.teamCode] || 0) + 1;
    } catch (e: any) {
      failed++;
      console.error(`  ✗ ${p.name} (${p.teamCode}): ${e.message}`);
    }
  }

  console.log(`✓ Seeded ${inserted} players across ${Object.keys(teamCounts).length} teams`);
  if (failed > 0) console.log(`✗ ${failed} failed`);
}

main().catch((err) => {
  console.error("Failed:", err);
  process.exit(1);
});
