/**
 * Seed the players table from the static squads JSON.
 *
 * Run with: node --experimental-strip-types scripts/seed-players.ts
 *
 * Requires DATABASE_URL in .env.local
 * Data source: scripts/data/squads.json (generated by parse-fifa-squads.ts)
 */

import { readFileSync } from "fs";

const envFile = readFileSync(".env.local", "utf-8");
for (const line of envFile.split("\n")) {
  const match = line.match(/^([^#=]+)=["']?(.+?)["']?$/);
  if (match) process.env[match[1].trim()] = match[2].trim();
}

interface SquadPlayer {
  teamCode: string;
  teamName: string;
  name: string;
  position: string;
  number: number;
}

const BATCH_SIZE = 200;

async function main() {
  const squadsPath = "scripts/data/squads.json";
  const players: SquadPlayer[] = JSON.parse(readFileSync(squadsPath, "utf-8"));
  console.log(`Loaded ${players.length} players from ${squadsPath}`);

  const { neon } = await import("@neondatabase/serverless");
  const sql = neon(process.env.DATABASE_URL!);

  await sql`DELETE FROM players`;
  console.log("Cleared existing players.\nSeeding database...\n");

  let inserted = 0;
  for (let i = 0; i < players.length; i += BATCH_SIZE) {
    const batch = players.slice(i, i + BATCH_SIZE);
    const params: (string | number)[] = [];
    const placeholders = batch.map((p, j) => {
      const offset = j * 4;
      params.push(p.teamCode, p.name, p.position, p.number);
      return `($${offset + 1}, $${offset + 2}, $${offset + 3}, $${offset + 4})`;
    }).join(", ");

    await sql.query(
      `INSERT INTO players (team_id, name, position, number) VALUES ${placeholders}
       ON CONFLICT (team_id, name) DO UPDATE SET position = EXCLUDED.position, number = EXCLUDED.number`,
      params,
    );

    inserted += batch.length;
    console.log(`  Batch ${Math.floor(i / BATCH_SIZE) + 1}: ${batch.length} players (${inserted}/${players.length})`);
  }

  const teams = new Set(players.map((p) => p.teamCode));
  console.log(`\n✓ Seeded ${inserted} players across ${teams.size} teams`);
}

main().catch((err) => {
  console.error("Failed:", err);
  process.exit(1);
});
